JPackageCreateInstallerTest-1.0.msi
JPackageCreateInstallerWinMenuTest-1.0.msi
JPackageCreateInstallerWinMenuGroupTest-1.0.msi
JPackageCreateInstallerWinPerUserInstallTest-1.0.msi
JPackageCreateInstallerFileAssociationsTest-1.0.msi
ECHO Make sure that installer asks to select installation location. Install to default one.
JPackageCreateInstallerWinDirChooserTest-1.0.msi
JPackageCreateInstallerWinRegistryNameTest-1.0.msi
JPackageCreateInstallerWinShortcutTest-1.0.msi
ECHO Make sure that installer shows license
JPackageCreateInstallerLicenseTest-1.0.msi
JPackageCreateInstallerWinUpgradeUUIDTest-1.0.msi
JPackageCreateInstallerWinUpgradeUUIDTest-2.0.msi
JPackageCreateInstallerInstallDirTest-1.0.msi
JPackageCreateInstallerFileAssociationsInstallDirTest-1.0.msi
PAUSE
