= HotCode Agent

== Build

Make sure you have JDK 17 installed and `JAVA_HOME` points to the installation path. Use Maven.

[source,shell]
----
JAVA_HOME=/usr/lib/jvm/bellsoft-java17-amd64 mvn clean install
----

== Usage

=== Live Mode

The agent is loaded into by using JVM option `-javaagent`, i.e.

[source,shell]
----
java -javaagent:hotcode-agent-1.0-SNAPSHOT.jar \
  -XX:+HotCodeHeap -jar application.jar
----

It automatically starts a JFR recording, collects execution profiling data, generates a list of hot methods, turns it
into compiler directives and, finally, applies these directives to VM.

The directives are stored in a temporary file in the following format:
[source,text]
----
{
        match: [
                "dotty/tools/dotc/core/Types$TypeMap mapOver (Ldotty/tools/dotc/core/Types$Type;)Ldotty/tools/dotc/core/Types$Type;",
                "dotty/tools/tasty/TastyHash$ pjwHash64 ([B)J",
        ],
        c2: {
                Hot: true,
        },
},
----

The agent can be configured with a few options by appending them to the JAR filename. The options are separated by
comma.

Supported options are:

* delay -- time between the agent activation and first profiling, default is 10 minutes;
* period -- time between profiling iterations, default is 0m (no repetitions);
* interval -- sampling interval during profiling, default is 10 milliseconds;
* duration -- profiling iteration duration, default is 60 seconds;
* top -- total maximum number of hottest methods to mark, default is 1000;
* chunk -- maximum number of new hot methods marked at once, equals to top for one time profiling, default is 100 for periodic profiling;
* print -- if true, collected profile is printed to stdout, default is false;

For example:

[source,shell]
----
java -javaagent:hotcode-agent-1.0-SNAPSHOT.jar=interval=50ms,delay=1h,top=100 \
  -XX:+HotCodeHeap -jar application.jar
----

instructs the agent to run the profiling once, 1 hour after the JVM start, with a default duration of 300 seconds and a sampling interval of 50 milliseconds, and move 100 hottest methods to the hot code heap.

All unrecognized options are ignored. When an invalid option value occurs then the default value is used.

[NOTE]
====
All time intervals should be specified with time units, the supported time units are:

* ms -- milliseconds;
* s -- seconds;
* m -- minutes;
* h -- hours;
* d -- days;

For example:

[source,text]
----
200ms -- 200 milliseconds;
90s -- 90 seconds;
2d -- 2 days;
----

complex durations are possible as well:

----
5hd16m100ms -- 5 hours 16 minutes and 100 milliseconds;
1439m60s -- 1 day (= 1440 minutes = 24 hours = 1 day)
----

No uppercase, no spaces are allowed.

====

=== Offline Mode

The agent can be executed as a standalone application. Supported commands:

* `convert` -- analyze existing recordings or connect to JFR events repository. In the second scenario it doesn't analyze any previous events, instead, it consumes only new ones and only when the stream is closed, it does the analysis and shows the report.
* `attach` -- dynamically inject itself into the running JVM.

For instance:
[source,shell]
----
java -jar hotcode-agent-1.0-SNAPSHOT.jar convert recording.jfr
java -jar hotcode-agent-1.0-SNAPSHOT.jar attach 1234 --duration 10s --period 1h
----

The full list of options and arguments can be obtained by running the agent with `-h` option:

[source,shell]
----
java -jar hotcode-agent-1.0-SNAPSHOT.jar -h
----

After the recording stream is closed, `convert` outputs the summary report, i.e.

[source, shell]
----

----------------------------------------------------------------------------------------------------------------------
| COUNT   | %         | METHOD                                                                                       |
----------------------------------------------------------------------------------------------------------------------
|     42  |      6.74 | denot(Ldotty/tools/dotc/core/Contexts$Context;)Ldotty/tools/dotc/core/Denotations$Denotation;|
|     41  |      6.58 | apply(Ljava/lang/Object;)Lscala/runtime/BoxedUnit;                                           |
|     31  |      4.98 | enterIfNew([CII)Ldotty/tools/dotc/core/Names$SimpleName;                                     |
|     29  |      4.65 | map(Lscala/Function1;)Lscala/collection/immutable/List;                                      |
|     26  |      4.17 | mapOver(Ldotty/tools/dotc/core/Types$Type;)Ldotty/tools/dotc/core/Types$Type;                |
|     25  |      4.01 | adjustedOffset(I)I                                                                           |
----------------------------------------------------------------------------------------------------------------------



----

and generates the compiler directives file, based on the analysis.

== Useful target JVM options

For diagnostics consider printing more info about code cache.

----
-XX:+PrintCodeCache -Xlog:codecache
----

JFR overhead depends not only on the interval but also on global settings like stack depth. Default value (64) can be decreased.

----
-XX:FlightRecorderOptions=stackdepth=16
----

For some benchmarks it is useful to fix code cache and disable flushing.

----
-XX:ReservedCodeCacheSize=2G -XX:InitialCodeCacheSize=2G -XX:+HotCodeHeap -XX:HotCodeHeapSize=32M -XX:-UseCodeCacheFlushing
----

It makes sense to ensure that dynamic agent loading in on.

----
-XX:+EnableDynamicAgentLoading
----
