JPackageCreateInstallerTest-1.0.exe
JPackageCreateInstallerWinMenuTest-1.0.exe
JPackageCreateInstallerWinMenuGroupTest-1.0.exe
JPackageCreateInstallerWinPerUserInstallTest-1.0.exe
JPackageCreateInstallerFileAssociationsTest-1.0.exe
ECHO Make sure that installer asks to select installation location. Install to default one.
JPackageCreateInstallerWinDirChooserTest-1.0.exe
JPackageCreateInstallerWinRegistryNameTest-1.0.exe
JPackageCreateInstallerWinShortcutTest-1.0.exe
ECHO Make sure that installer shows license
JPackageCreateInstallerLicenseTest-1.0.exe
JPackageCreateInstallerWinUpgradeUUIDTest-1.0.exe
JPackageCreateInstallerWinUpgradeUUIDTest-2.0.exe
JPackageCreateInstallerInstallDirTest-1.0.exe
JPackageCreateInstallerFileAssociationsInstallDirTest-1.0.exe
PAUSE
